services:
  - type: web
    name: vhr-dashboard-backend
    env: docker
    branch: main
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: STRIPE_SECRET_KEY
      - key: JWT_SECRET
      - key: STRIPE_DEBUG_PRICES
      - key: NO_ADB
        value: '1'
      - key: PORT
      - key: HOST
      - key: HEALTH_CHECK_PATH
        value: "/_status"
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-11-openjdk-amd64"
      - key: GRADLE_HOME
        value: "/opt/gradle/gradle-8.7"
